In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import precision_recall_fscore_support
import warnings
warnings.filterwarnings('ignore')

C:\Users\Gobinath\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
C:\Users\Gobinath\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
C:\Users\Gobinath\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior an

In [2]:
tr = pd.read_csv(r"C:\Users\Gobinath\teddy bro class\csv_files\train.csv")
tr.head(100)
ts = pd.read_csv(r"C:\Users\Gobinath\teddy bro class\csv_files\test.csv")
ts.head(10)
tr.head(100)

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0             842     0          2.2         0   1       0           7    0.6   
1            1021     1          0.5         1   0       1          53    0.7   
2             563     1          0.5         1   2       1          41    0.9   
3             615     1          2.5         0   0       0          10    0.8   
4            1821     1          1.2         0  13       1          44    0.6   
..            ...   ...          ...       ...  ..     ...         ...    ...   
95           1137     1          1.0         0  18       0           7    1.0   
96           1355     0          2.3         0  10       1          23    0.2   
97           1665     1          0.5         0   3       1          60    0.2   
98            657     0          2.5         0   0       0          37    0.7   
99            593     0          0.5         0   6       0          31    0.4   

    mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0         188        2  ...         20       756  2549     9     7         19   
1         136        3  ...        905      1988  2631    17     3          7   
2         145        5  ...       1263      1716  2603    11     2          9   
3         131        6  ...       1216      1786  2769    16     8         11   
4         141        2  ...       1208      1212  1411     8     2         15   
..        ...      ...  ...        ...       ...   ...   ...   ...        ...   
95        196        3  ...        942      1179  3616    13     5         12   
96        132        5  ...        651       891   880    19     4          8   
97        194        6  ...       1572      1684  1601    18    17         14   
98        141        2  ...        476       961  1412    14     3         18   
99        156        7  ...       1233      1317  1692     6     2          7   

    three_g  touch_screen  wifi  price_range  
0         0             0     1            1  
1         1             1     0            2  
2         1             1     0            2  
3         1             0     0            2  
4         1             1     0            1  
..      ...           ...   ...          ...  
95        1             1     1            3  
96        1             1     0            0  
97        1             0     0            2  
98        0             1     0            0  
99        1             0     0            1  

[100 rows x 21 columns]

In [3]:
x = tr.iloc[:,:-1]
y = tr.loc[:,"price_range"]

In [5]:
x.shape

(2000, 21)

In [4]:
x.head(10)

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   
5           1859     0          0.5         1   3       0          22    0.7   
6           1821     0          1.7         0   4       1          10    0.8   
7           1954     0          0.5         1   0       0          24    0.8   
8           1445     1          0.5         0   0       0          53    0.7   
9            509     1          0.6         1   2       1           9    0.1   

   mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2   2         20       756  2549     9     7         19   
1        136        3   6        905      1988  2631    17     3          7   
2        145        5   6       1263      1716  2603    11     2          9   
3        131        6   9       1216      1786  2769    16     8         11   
4        141        2  14       1208      1212  1411     8     2         15   
5        164        1   7       1004      1654  1067    17     1         10   
6        139        8  10        381      1018  3220    13     8         18   
7        187        4   0        512      1149   700    16     3          5   
8        174        7  14        386       836  1099    17     1         20   
9         93        5  15       1137      1224   513    19    10         12   

   three_g  touch_screen  wifi  
0        0             0     1  
1        1             1     0  
2        1             1     0  
3        1             0     0  
4        1             1     0  
5        1             0     0  
6        1             0     1  
7        1             1     1  
8        1             0     0  
9        1             0     0

In [5]:
y.head(10)

0    1
1    2
2    2
3    2
4    1
5    1
6    3
7    0
8    0
9    0
Name: price_range, dtype: int64

In [6]:
x = np.asanyarray(tr.iloc[:,:])
y = np.asanyarray(tr.loc[:,"price_range"])

In [7]:
x.shape

(2000, 21)

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.4,random_state = 90)
logi = LogisticRegression()
logi.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [7]:
y_pred = logi.predict(x_test)

In [8]:
vis = pd.DataFrame({"Actual:" : y_test,
                    "predicted:":y_pred})

In [9]:
print(vis)

     Actual:  predicted:
699        0           0
146        1           1
777        3           3
894        2           1
676        3           3
..       ...         ...
500        0           1
564        2           3
101        1           1
236        1           0
127        1           1

[800 rows x 2 columns]


In [10]:
conf_mat = confusion_matrix(y_test,y_pred)
print(conf_mat)

[[177  19   1   0]
 [ 34 124  39   0]
 [  0  47 111  45]
 [  0   0   6 197]]


In [11]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.90      0.87       197
           1       0.65      0.63      0.64       197
           2       0.71      0.55      0.62       203
           3       0.81      0.97      0.89       203

    accuracy                           0.76       800
   macro avg       0.75      0.76      0.75       800
weighted avg       0.75      0.76      0.75       800



In [12]:
from sklearn.metrics import plot_roc_curve
svc_disp = plot_roc_curve(logi, x_test, y_test)
plt.show()


ROC Curve with Visualization API
Scikit-learn defines a simple API for creating visualizations for machine
learning. The key features of this API is to allow for quick plotting and
visual adjustments without recalculation. In this example, we will demonstrate
how to use the visualization API by comparing ROC curves.



TypeError: 'module' object is not callable

In [13]:
import sklearn.metrics as metrics

In [14]:
probs = logi.predict_proba(x_test)
preds = probs[:,1]
fpr, tpr, threshold = metrics.roc_curve(y_test, y_pred)
roc_auc = metrics.auc(fpr, tpr)

# method I: plt
import matplotlib.pyplot as plt
plt.title('Receiver Operating Characteristic')
plt.plot(fpr, tpr, 'b', label = 'AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],'r--')
plt.xlim([0, 1])
plt.ylim([0, 1])
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()


ValueError: multiclass format is not supported

In [16]:
import sklearn.metrics as metrics
# calculate the fpr and tpr for all thresholds of the classification
probs = logi.predict_proba(x_test)
preds = probs[:,1]
fpr, tpr, threshold = metrics.roc_curve(y_test,y_pred)
roc_auc = metrics.auc(fpr, tpr)

plt.title('Receiver Operating Characteristic')
plt.plot(fpr, tpr, 'b', label = 'AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],'r--')
plt.xlim([0, 1])
plt.ylim([0, 1])
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()

ValueError: multiclass format is not supported